### ISSUE TITLE
Cannot import module in venv

### ISSUE THREAD

**Issue by ryanwalder** [devopsarr/radarr-py#51]
I've installed the module in a venv but am getting errors when trying to import it:

1. `python -m venv /tmp/foo`
2. `cd /tmp/foo`
4. `source bin/activate`
5. `pip install git+https://github.com/devopsarr/radarr-py.git`
6. `python`
7. (in python) `import radarr`

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/foo/lib/python3.11/site-packages/radarr/__init__.py", line 22, in <module>
    from radarr.api.alternative_title_api import AlternativeTitleApi
  File "/tmp/foo/lib/python3.11/site-packages/radarr/api/__init__.py", line 48, in <module>
    from radarr.api.log_file_api import LogFileApi
  File "/tmp/foo/lib/python3.11/site-packages/radarr/api/log_file_api.py", line 22, in <module>
    from pydantic import field_validator
ImportError: cannot import name 'field_validator' from 'pydantic' (/tmp/foo/lib/python3.11/site-packages/pydantic/__init__.cpython-311-x86_64-linux-gnu.so)
```

venv packages:

```
/tmp/foo $ pip list
Package            Version
------------------ ----------
aenum              3.1.15
certifi            2023.11.17
charset-normalizer 3.3.2
idna               3.6
pip                23.2.1
pydantic           1.10.13
python-dateutil    2.8.2
radarr-py          0.4.0
requests           2.31.0
setuptools         68.2.2
six                1.16.0
typing_extensions  4.9.0
urllib3            2.1.0
wheel              0.41.2
```

**Comment by davidgibbons** [comment]
I get the same error, it looks like maybe changes were made to support pydantic 2 that aren't backwards compatible. If I pip install pydantic==2  I can get past the import error, although I get field required errors instead. It's at least a code exception instead of a import error. 
It seems like the older 0.4.0 released version on pypi doesn't have that issue but it also seems out of date compared to the api.

**Comment by ryanwalder** [comment]
@Fuochi No worries for the late response, thanks for taking the time to update things. Just given it a quick test (just loading the module) and it works as expected. Thanks again!
